### ISSUE TITLE
[require-super-in-lifecycle-hooks] False negative with Glimmer components?

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/eslint-plugin-ember#1035]
Overriding `willDestroy` in a Glimmer component and not calling `super.willDestroy` should lead to a linter warning... perhaps? Not sure if it is "mandatory" to call the super method?

**Comment by bmish** [comment]
Sounds like a bug. My assumption is that `super` should be called in Glimmer component hooks too.

**Comment by boris-petrov** [comment]
@bmish - thanks!

I found another false-negative. `willDestroy` in classic components is also not caught.

**Comment by bmish** [comment]
@boris-petrov in classic components, the hook is called `willDestroyElement`, so I think we're fine there: https://guides.emberjs.com/v3.4.0/components/the-component-lifecycle/

**Comment by bmish** [comment]
Actually, it looks like classic components do have a `willDestroy` too: https://api.emberjs.com/ember/3.22/classes/Component/methods/willDestroy?anchor=willDestroy

**Comment by bmish** [comment]
@boris-petrov updated rule to catch `willDestroy` in both glimmer and non-glimmer components.
