### ISSUE TITLE
New rule: Prevent usage of `htmlSafe`

### ISSUE THREAD

**Issue by patocallaghan** [ember-cli/eslint-plugin-ember#1041]
Any thoughts on adding a rule to prevent usage of `htmlSafe`? `htmlSafe`, when not used properly, can be a vector for XSS and in some codebases it's preferred to prevent it.

ember-template-lint has a [similar rule](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-triple-curlies.md) which prevents usage of triple curlies: `{{{test}}}`. 

I was thinking we could just test for usages of the following? 

```js
import { htmlSafe } from '@ember/string';
```

I'd be happy to put it together if there's interest?

**Comment by bmish** [comment]
Seems reasonable.

There's also this import and I'm not sure what the difference is between the function from `@ember/string` and `@ember/template`:

```js
import { htmlSafe } from '@ember/template';
```

https://api.emberjs.com/ember/release/functions/@ember%2Ftemplate/htmlSafe

Targeting the import statement with the new rule sounds fine.

And note that we have a separate rule [no-string-prototype-extensions](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-string-prototype-extensions.md) which already disallows the string prototype version `'foo'.htmlSafe()` so we don't need to worry about that.

**Comment by robclancy** [comment]
Why would you prevent this? The reason it exists is so you don't do the triple curlies and explicitly control when something is safe.

**Comment by patocallaghan** [comment]
@robclancy so in my case we'd want to prevent all usage of triple curlies AND `htmlSafe` in JS too. I've actually found `htmlSafe` to be a misnomer because some people have unwittingly used it thinking it _makes_ your HTML safe and can be a vector for XSS. There's an old RFC which proposes [renaming it to be more explicit](https://github.com/emberjs/rfcs/pull/443). 

I know this rule won't be for every app hence why it should not be `recommended` but in my use case it would be useful.
