### ISSUE TITLE
Installation problem, possible documentation missing

### ISSUE THREAD

**Issue by Baukereg** [ember-cli/eslint-plugin-ember#106]
I'm trying to get this plugin working in an Ember addon, but after installation (as described in the documentation) I still get this error:

```
Definition for rule 'ember/no-old-shims' was not found  ember/no-old-shims
```

This addon is added to my package. Ember-cli-eslint is installed as well.

```
"ember-cli-eslint": "^3.0.0",
...
"eslint-plugin-ember": "^4.0.0",
```

And I can see it in the node_modules folder as well. My .eslintrc looks like this:

```
module.exports = {
  root: true,
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module'
  },
  extends: [
    'eslint:recommended'
  ],
  env: {
    browser: true
  },
  rules: {
    'ember/no-old-shims': 2
  }
};
```

If there is a step I'm missing, it might be something missing from the documentation as well.

**Comment by michalsnik** [comment]
Hey @Baukereg, it looks like you didn't extend the `plugin:ember/recommended` config.
Try this:
```
module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:ember/recommended'
  ],
  rules: {
    // override rules' settings here
    'ember/no-old-shims': 2
  }
}
```

**Comment by michalsnik** [comment]
I just tested it on a new project and it works like charm :)

**Comment by GCorbel** [comment]
Sorry to comment this old issue but I have the same behavior. 

I have this `.eslintrc.js` : 

```
module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:ember/recommended'
  ],
  rules: {
    'ember/no-old-shims': 2
  }
};
```

I have this in my package.json : 

    "babel-eslint": "^8.2.1",
    "ember-cli-eslint": "^4.2.3",
    "eslint": "^3.19.0",
    "eslint-plugin-ember": "^5.0.3"

It works for other rules.

**Comment by GCorbel** [comment]
It's correct. I installed eslint globally and I updated eslint-plugin-ember locally. I just did `yarn global add eslint-plugin-ember` and it works.
