### ISSUE TITLE
New Rule `no-array-prototype-extensions`

### ISSUE THREAD

**Issue by bmish** [ember-cli/eslint-plugin-ember#1075]
Similar to `no-string-prototype-extensions` and `no-function-prototype-extensions`.

Would check for many of these functions: https://api.emberjs.com/ember/release/classes/MutableArray

https://guides.emberjs.com/release/configuring-ember/disabling-prototype-extensions/

**Comment by smilland** [comment]
Hi @bmish , I am working on an RFC for deprecating array prototype extensions and would love to contribute to this new rule. One thing to be careful of is `replace`. It's also part of original string prototypes.
