### ISSUE TITLE
[require-valid-css-selector-in-test-helpers] `[data-foo` without the closing bracket is a valid CSS selector

### ISSUE THREAD

**Issue by bartocc** [ember-cli/eslint-plugin-ember#1097]
Looks like `[data-foo` is a valid selector. Notice there is no closing `]` in the selector.

I've tested it under Chrome, FF and Safari dev tools and they all select the element `<div data-foo>`

The `require-valid-css-selector-in-test-helpers` rule on the other hand considers this to be a bad selector.

**Comment by bmish** [comment]
The rule documentation for [require-valid-css-selector-in-test-helpers](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/require-valid-css-selector-in-test-helpers.md) mentions this:

> One example of invalid CSS selectors which do not cause failing tests is when using unclosed attribute selector blocks. Tests happen to pass today in this case due to a quirk in the CSS selector spec which is marked as WontFix by Chromium.

It seems desirable to me to have the lint rule fix up missing braces even if they still happen to work.

CC: @jsturgis

**Comment by jsturgis** [comment]
The Lint rule will fix this case automatically if you use the `--fix` option. The lack of a closing brace is not a valid selector but browsers will "auto-close" the selector brace to make it work, similar to how browsers will add missing closing tags in HTML.

**Comment by bartocc** [comment]
thx for the feedback 👍
