### ISSUE TITLE
New rule: "no-send-action"

### ISSUE THREAD

**Issue by jbandura** [ember-cli/eslint-plugin-ember#112]
Import "no-send-action" rule from @chadhietala's https://github.com/ember-best-practices/eslint-plugin-ember-best-practices/blob/master/guides/rules/no-send-action.md

**Comment by kevinkucharczyk** [comment]
Isn't this already implemented here as [closure-actions](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/closure-actions.md)?

**Comment by michalsnik** [comment]
@kevinkucharczyk is right, we already have it
