### ISSUE TITLE
no-get autofix is running on ObjectProxies

### ISSUE THREAD

**Issue by rogeraraujo90** [ember-cli/eslint-plugin-ember#1141]
We are getting troubles in my project with `eslint autofix on save` and the `no-get` rule.

An ObjectProxy file that uses the classic Mixin system:

```javascript
export default MyProxyObject extends ObjectProxy.extend(SomeMixin) { 
  method() {
    const property = this.get('property')
  }
 }
```

In this condition the `no-get` rule triggers an error that will be auto-fixed on save.

This should not be logged as an error because we got an error if trying access properties without `.get` in ObjectProxy.

Because I'm under a NDA I cannot share my code. But if some additional detail is needed I can answer.

**Comment by bmish** [comment]
Looks like this is a bug. The `ember/no-get` rule already tries to ignore object/array proxies, but it looks like this variation with `ObjectProxy.extend(SomeMixin)` is not handled.

This should be a valid test case added to the rule:

```js
import ObjectProxy from '@ember/object/proxy';
export default class MyProxyObject extends ObjectProxy.extend(SomeMixin) { 
    method() {
        const property = this.get('property');
    }
}
```
