### ISSUE TITLE
Best practice for `requireServiceNames` of `require-computed-property-dependencies.md`

### ISSUE THREAD

**Issue by Baukereg** [ember-cli/eslint-plugin-ember#1154]
Rule: https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/require-computed-property-dependencies.md

The default value of the `requireServiceNames` option is set to `false`. To me it doesn't make sense to have services (like `store`) as a dependency. But I can't find any recommendations or best practices.

Does it make sense to set this rule to `true` by default, or is there a good reason not to?

**Comment by bmish** [comment]
There was a previous discussion about why we ignore service names here: https://github.com/ember-cli/eslint-plugin-ember/issues/477
