### ISSUE TITLE
`no-unused-services` rule should account for observer dependent keys

### ISSUE THREAD

**Issue by bmish** [ember-cli/eslint-plugin-ember#1157]
CC: @lin-ll

**Comment by lin-ll** [comment]
Just realized that there's also `@observes('prop')` right? Is that something that needs to be supported? @bmish

**Comment by bmish** [comment]
I could be wrong but I think there's no observer decorator?

**Comment by lin-ll** [comment]
Personally haven't seen it, but found this when I was looking around: https://github.com/ember-decorators/ember-decorators/blob/master/packages/object/addon/index.js#L29

**Comment by bmish** [comment]
I see it documented here: https://ember-decorators.github.io/ember-decorators/docs/api/modules/@ember-decorators/object#observes

So it looks like we might as well support it.
