### ISSUE TITLE
New rule: `no-implicit-injections`

### ISSUE THREAD

**Issue by nelstrom** [ember-cli/eslint-plugin-ember#1178]
With the [release of Ember 3.26](https://blog.emberjs.com/ember-3-26-released):

> Implicit injection has been deprecated. In particular, the store service from Ember Data must be explicitly injected into controllers and routes if they refer to this.store.

More details in [the deprecation guide](https://deprecations.emberjs.com/v3.x/#toc_implicit-injections). We should add a rule that flags up implicit injections.

For the common case of using `this.store`, it should be pretty straightforward to implement a fixer too.

**Comment by nelstrom** [comment]
Note that #195 proposes a rule called `no-implicit-injections`, which sounds similar but the motivation behind it is based on recommended 'best practices', whereas this proposal is based on a deprecation.

**Comment by bmish** [comment]
Regarding rule naming:

I actually think we should name the rule from #195 `no-implicit-service-injection-argument` to be more specific about what that is actually referring to, and then we can name your rule `no-implicit-injections` to match how the deprecation describes it.

**Comment by bmish** [comment]
I opened a PR to implement `no-implicit-service-injection-argument`: #1188
