### ISSUE TITLE
Rule to disallow jQuery

### ISSUE THREAD

**Issue by cibernox** [ember-cli/eslint-plugin-ember#123]
In #121 I've created a rule to disallow usage of `this.$` in components and tests, which brings us closer to a rule that disallows jQuery but it's not everything we should use.

This of patterns that use jQuery (not all of them can be "linted")
- `this.$`
- `import whatever from 'jquery';`
- `Ember.$`
- `const { $ } = Ember;`
- Apps that don't have `ember-native-dom-event-dispatcher` among their dev dependencies.

I'd like to create a rule that prevents all (most?) patterns above.

**Comment by michalsnik** [comment]
I'd go with `no-implicit-jquery` and block usage of:
- `this.$`
- `Ember.$`
for start, then we can revise it

**Comment by michalsnik** [comment]
Released in `v4.5.0`
