### ISSUE TITLE
running --fix w/ ember/use-ember-get-and-set messes up my code

### ISSUE THREAD

**Issue by jonathanong** [ember-cli/eslint-plugin-ember#130]
<img width="636" alt="screen shot 2017-08-14 at 4 12 50 pm" src="https://user-images.githubusercontent.com/643505/29295845-8d63733a-810b-11e7-9c62-ad8b7448c4e9.png">
<img width="630" alt="screen shot 2017-08-14 at 4 13 33 pm" src="https://user-images.githubusercontent.com/643505/29295846-8d74b8a2-810b-11e7-9175-7f31321c30eb.png">

seems like `Ember, Ember,`s keep getting added every time i run `--fix`

**Comment by michalsnik** [comment]
Hi @jonathanong! Thanks for posting this issue. I'll try to confirm it soon.

**Comment by michalsnik** [comment]
@sudowork can you please also take a look, I remember you were working on this recently :)

**Comment by sudowork** [comment]
Yes, I can take a look shortly @michalsnik
