### ISSUE TITLE
Remove opinionated configurations

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/eslint-plugin-ember#134]
In ESLint it is common to have `eslint-plugin-*` project that provide custom rules and `eslint-config-*` projects that provide custom configurations (aka. rulesets). IMHO this project should only provide the custom rules for Ember projects, but no opinionated configurations. Instead opinionated configurations should be provided by projects like https://github.com/simplabs/eslint-config-simplabs and https://github.com/DockYard/eslint-plugin-ember-suave.

If we decide that we want to keep the configuration here then we should discuss what rules to recommend since this is an official Ember CLI project now and people are apparently starting to adopt those recommendations (see https://github.com/emberjs/ember.js/issues/15590#issuecomment-323342930)

/cc @rwjblue @michalsnik

**Comment by jbandura** [comment]
How about keeping only rules which provide educational value (e.g. `use-brace-expansions', 'avoid-leaking-state-in-components`) as recommended? I guess that the most likely candidates to be turned off as being too opinionated would be `use-ember-get-and-set` and all the `order-in-*` rules. I feel that all the others provide real value, such as preventing unexpected behaviour or warning about deprecations and could be another way for the ember core team to provide additional guidance for developers when introducing deprecations and/or introducing new features. WDYT?

**Comment by michalsnik** [comment]
@Turbo87 I completely agree with @jbandura.

First of all Ember is an opinionated framework for a reason, and one of it's biggest advantages is the fact, that you get everything by default and you can straight away start shipping features. I think we should keep this spirit here and provide simplest possible way of supporting developers writing better code without the need to look for additional configs.

Second of all given the ability to ship configuration together with plugin we have a great advantage of providing additional feedback and guidance as @jbandura mentioned. If we'll remove config, we'll introduce more confusion in my opinion.

If someone want's to use other config then he's totally not bound to anything here. Built-in config just makes the life a little easier and I'm strongly for leaving it after discussing which rules should be recommended and which should be not.

**Comment by Turbo87** [comment]
@jbandura @michalsnik the problem with having the config in the repo is that whenever a useful rule is added that we want to add to the `recommended` set we will have to do a major release since it's essentially a breaking change if people depend on that preset

**Comment by rwwagner90** [comment]
FWIW, I would be in favor of voting on rules and doing some sort of RFC process or something, that way we can recommend a preset for ember projects to try to standardize things across the community. Everyone is going to have different opinions on things like spacing, etc, but rules that are good Ember practices should be an easy set for most people to agree on enforcing, I, for one, would be fine giving up some of my own Ember preferences, like using `this.get` for hopefully gaining more consistency across projects.

**Comment by michalsnik** [comment]
@rwwagner90 I'll prepare PR on which we can further iterate and discuss importance of enabling/disabling specific rules.
I get your point totally @Turbo87 but I already went this road with `eslint-plugin-netguru-ember` and `eslint-config-netguru-ember` and keeping both repositories in sync is a pain in the ass and it may lead to more false positives and confusion.

**Comment by rwwagner90** [comment]
@michalsnik definitely keep me posted. Happy to help and weigh in whenever needed 😄

**Comment by Turbo87** [comment]
this was mostly resolved by https://github.com/ember-cli/eslint-plugin-ember/pull/146
