### ISSUE TITLE
[BUG] ember/use-ember-get-and-set auto-fix

### ISSUE THREAD

**Issue by Exelord** [ember-cli/eslint-plugin-ember#135]
Hi,
The auto-fix for `ember/use-ember-get-and-set` behaves very unexpected:
<img width="931" alt="screen shot 2017-08-30 at 15 16 17" src="https://user-images.githubusercontent.com/1469375/29874227-6890e9b0-8d96-11e7-9e17-234d6387974b.png">

Probably needs some adjustments.

**Comment by michalsnik** [comment]
Hi @Exelord,

We already had the same issue reported: https://github.com/ember-cli/eslint-plugin-ember/issues/130

It's fixed in `v4.4.0` and up :)
