### ISSUE TITLE
Disallow duplicate name in class members (no-dupe-class-members)

### ISSUE THREAD

**Issue by michaelbdai** [ember-cli/eslint-plugin-ember#1371]
https://eslint.org/docs/rules/no-dupe-class-members
We should not allow duplicate name in class members. It should never intentional but may be introduced by merge conflict. This rule can help catch it.

**Comment by bmish** [comment]
What's the suggestion? Won't the ESLint rule already handle this?

**Comment by bmish** [comment]
Yep. I would recommend following the linting used in the default ember-cli blueprint: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/.eslintrc.js

Ember apps generally used the `recommended` configurations from eslint, eslint-plugin-ember, eslint-plugin-node, eslint-plugin-qunit, prettier.
