### ISSUE TITLE
Use named functions defined on objects to handle promises (ember/named-functions-in-promises) where everything is ok!

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/eslint-plugin-ember#140]
Something I don't understand!

![error](https://user-images.githubusercontent.com/21275217/30186499-18bf2492-9426-11e7-96be-71ff2cdac494.PNG)
![errordescription](https://user-images.githubusercontent.com/21275217/30186503-1b389708-9426-11e7-9f26-0ba4e1a8593e.PNG)

Why this is an error?

```javascript
  actions: {
    confirm() {
      let post = Ember.get(this, "context");
      post.save().catch(() => this._notify(post));
    }
  },
```

**Comment by michalsnik** [comment]
Hey @johnunclesam , I think explanation of your problem is right here: https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/named-functions-in-promises.md
