### ISSUE TITLE
"named-functions-in-promises" on a small small small function!

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/eslint-plugin-ember#141]
On this:

```javascript
function prop(type) {
    return get(type, newType).then(prop => prop);
  }
```

isn't crazy to give: `[eslint] Use named functions defined on objects to handle promises (ember/named-functions-in-promises)` ?

**Comment by rwjblue** [comment]
Not sure why you created a duplicate issue for this?

Closing in favor of #140.
