### ISSUE TITLE
order-in-controllers/routes/components treats init() as just another function

### ISSUE THREAD

**Issue by xomaczar** [ember-cli/eslint-plugin-ember#150]
Should `init()` be a special case, I find it weird that i need to scroll all the way down past my "actions" to see what gets set during initialization of one of these things.

**Comment by mansona** [comment]
I very much think this should be a special case. In the future when we are able to use "proper" classes this will all be done in the constructor which will no doubt be the first thing a developer will see when they enter a class. 

We should be encouraging people to put their init() at the top of the file in the mean time 👍

**Comment by rwjblue** [comment]
> We should be encouraging people to put their init() at the top of the file in the mean time

Completely agreed.
