### ISSUE TITLE
Cannot disable no-jquery for whole file

### ISSUE THREAD

**Issue by locks** [ember-cli/eslint-plugin-ember#1500]
I have a file that is using jQuery, so I added an `/* eslint-ignore ember/no-jquery */` at the top, to disable it for the whole file.
However, it still errors until I add an `eslint-disable-next-line` declaration right before the jQuery usage.

**Comment by bmish** [comment]
Note that the reason the above comment style is needed for this particular rule is that this rule does a search for jQuery references as soon as it sees the `Program` node for the file (before any line-specific disable comment would have been applied):

https://github.com/ember-cli/eslint-plugin-ember/blob/aaf0dd2e3ccd8502e137a0f2704e3aa3356818fa/lib/rules/no-jquery.js#L51
