### ISSUE TITLE
Add special case for super in ember/no-array-prototype-extensions

### ISSUE THREAD

**Issue by urbany** [ember-cli/eslint-plugin-ember#1553]
Can we safely ignore when obj is called super?

![Screenshot 2022-08-04 at 16 36 52](https://user-images.githubusercontent.com/50884/182888200-c9f48a5a-bb9c-4df0-b40a-2cad6e297eba.png)

Thanks in advance!

**Comment by bmish** [comment]
Yes sounds like a good fix to make.
