### ISSUE TITLE
alias-model-in-controller errors when route has no model to alias

### ISSUE THREAD

**Issue by petey** [ember-cli/eslint-plugin-ember#157]
It would be nice if this rule didn't care about controllers whose route doesn't expose a model.

**Comment by CvX** [comment]
Route by default exposes an implicit model hook. Per docs:

```
By default, if your route has a dynamic segment ending in _id:
* The model class is determined from the segment (post_id's class is App.Post)
* The find method is called on the model class with the value of the dynamic segment.
```

So linter couldn't really tell if there's a model in use or not.

You can't always just manually disable this rule per controller:
`/* eslint-disable ember/alias-model-in-controller */`

**Comment by paulbhartzog** [comment]
Is there a way to disable it in .eslintrc or for the whole app globally?

**Comment by CvX** [comment]
Yup, in .eslintrc.js:

```js
rules: {
  'ember/alias-model-in-controller': 'off',
}
```
