### ISSUE TITLE
Add `fix` for order-in-* rules

### ISSUE THREAD

**Issue by PrzemoRevolve** [ember-cli/eslint-plugin-ember#161]
I'd like to propose adding fixer for `order-in-*` rules. AFAIK the common logic for those rules can be found in `property-order` util, and there's the only `context.report()` call. The good thing is that the hard work is done already - finding the token before which the current one should be inserted.
I'd like to handle this task.

What do you think?

**Comment by rwjblue** [comment]
Generally speaking fixers are great! Happy to have more of our rules support auto-fixing.

**Comment by PrzemoRevolve** [comment]
@rwjblue yeah, there might be a tiny problem: in order to do that we need eslint >= 4.0.0.
Returning an array of fixes from fixer function is not supported in earlier versions, and that's what I'm doing: first removing the property from the wrong place, and then pasting it in the right place.
Is this acceptable?
