### ISSUE TITLE
Glimmer Processor can't handle errors without lines

### ISSUE THREAD

**Issue by wagenet** [ember-cli/eslint-plugin-ember#1683]
https://github.com/ember-cli/eslint-plugin-ember/blob/11556154cb026ffc58c521a778a8f776fa62f354/lib/preprocessors/glimmer.js#L107

Some errors do not have lines associated with them, so this does not work.

**Comment by wagenet** [comment]
```json
  message: {
    ruleId: null,
    fatal: true,
    severity: 2,
    message: 'Parsing error: ESLint was configured to run on `<tsconfigRootDir>/addons/luna/addon/components/util/cache-state.gts/0_/Users/pwagenet/Development/AuditBoard/auditboard-frontend/addons/luna/addon/components/util/cache-state.gts/0_/Users/pwagenet/Development/AuditBoard/auditboard-frontend/addons/luna/addon/components/util/cache-state.gts/0_/Users/pwagenet/Development/AuditBoard/auditboard-frontend/addons/luna/addon/components/util/cache-state.gts` using `parserOptions.project`: <tsconfigRootDir>/../../../../../users/pwagenet/development/auditboard/auditboard-frontend/tsconfig.json\n' +
      'However, that TSConfig does not include this file. Either:\n' +
      "- Change ESLint's list of included files to not include this file\n" +
      '- Change that TSConfig to include this file\n' +
      '- Create a new TSConfig that includes this file and include it in your parserOptions.project\n' +
      'See the TypeScript ESLint docs for more info: https://typescript-eslint.io/docs/linting/troubleshooting##i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file',
    line: undefined,
    column: undefined
  },
```

**Comment by NullVoxPopuli** [comment]
ah! all my tests didn't have parsing errors. good call out

**Comment by wagenet** [comment]
This would be fixed by #1667

**Comment by bwbuchanan** [comment]
> ```js
>   message: {
>     ruleId: null,
>     fatal: true,
>     severity: 2,
>     message: 'Parsing error: ESLint was configured to run on `<tsconfigRootDir>/addons/luna/addon/components/util/cache-state.gts/0_/Users/pwagenet/Development/AuditBoard/auditboard-frontend/addons/luna/addon/components/util/cache-state.gts/0_/Users/pwagenet/Development/AuditBoard/auditboard-frontend/addons/luna/addon/components/util/cache-state.gts/0_/Users/pwagenet/Development/AuditBoard/auditboard-frontend/addons/luna/addon/components/util/cache-state.gts` using `parserOptions.project`: <tsconfigRootDir>/../../../../../users/pwagenet/development/auditboard/auditboard-frontend/tsconfig.json\n' +
>       'However, that TSConfig does not include this file. Either:\n' +
>       "- Change ESLint's list of included files to not include this file\n" +
>       '- Change that TSConfig to include this file\n' +
>       '- Create a new TSConfig that includes this file and include it in your parserOptions.project\n' +
>       'See the TypeScript ESLint docs for more info: https://typescript-eslint.io/docs/linting/troubleshooting##i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file',
>     line: undefined,
>     column: undefined
>   },
> ```

@wagenet did you manage to solve the underlying issue with typescript-eslint (.gts file not included in tsconfig.json)?

I've tried adding `"**/*.gts"` to the includes in tsconfig.json, to no avail.

**Comment by wagenet** [comment]
@bwbuchanan unfortunately, I had to turn off type-aware lints in gts files. This is an issue others are aware of. I think we may have to update ESLint to be able to use Glint directly.

**Comment by bmish** [comment]
Note that this change was reverted:

* https://github.com/ember-cli/eslint-plugin-ember/pull/1920
* https://github.com/ember-cli/eslint-plugin-ember/pull/1941
