### ISSUE TITLE
Drop ESLint 3 support

### ISSUE THREAD

**Issue by t-sauer** [ember-cli/eslint-plugin-ember#180]
Currently this plugin supports eslint@3 which I think should be dropped in favor of 4.
One of the major advantages of ESLint 4 is an improved fixer API which allows to return multiple fixes. This would simplify the fixer for https://github.com/ember-cli/eslint-plugin-ember/pull/172 and would simplify writing fixers in general.

Since v5 is about to be released, I think this change should be included before that since it will need a major bump.

**Comment by rwjblue** [comment]
Sounds good to me. Mind sending in a PR (targeting the `next` branch)?

**Comment by rwjblue** [comment]
Discussed a bit in #81, and I think that instead of dropping support for ESLint 3 we should:

* Ensure CI runs for _both_ eslint@3 and eslint@4
* Expose utility methods to allow disabling of `--fix` support (for future use) when running under eslint older than 4

**Comment by rwjblue** [comment]
Completed in https://github.com/ember-cli/eslint-plugin-ember/pull/267
