### ISSUE TITLE
avoid-leaking-state-in-ember-objects: Easily add an ignored property?

### ISSUE THREAD

**Issue by mwpastore** [ember-cli/eslint-plugin-ember#182]
I'd like to add an additional ignored property to the avoid-leaking-state-in-ember-objects rule. It takes a list of ignored properties from the supplied options, but it's all-or-nothing: there's no easy way to add them. Can we modify this rule to merge in additional properties, or can we at least export the `DEFAULT_IGNORED_PROPERTIES` const from the module so I can append to it in .eslint.js?

**Comment by rwjblue** [comment]
@mwpastore - Ya, I think adding an `additionalIgnoredProperties` option seems reasonable to me...

**Comment by alexlafroscia** [comment]
Maybe instead of clobbering the list of defaults, the provided list of additive? I can't imagine the desired behavior ever being to remove any of the default ignored properties, so it seems like merging the two would make more sense.

**Comment by mwpastore** [comment]
Isn't that what I said?

**Comment by alexlafroscia** [comment]
Just giving my support for merging the lists, rather than exposing the defaults and making the configure-er merge them manually.

**Comment by mnoble01** [comment]
The list is additive for [avoid-leaking-state-in-components](https://github.com/ember-cli/eslint-plugin-ember/blob/master/lib/rules/avoid-leaking-state-in-components.js#L40-L48). Any reason this one shouldn't be the same?

**Comment by travis-jm** [comment]
@clcuevas  Is there a reason the most recent PR for this was closed instead of merged? Just curious because I could use this exact functionality.

**Comment by clcuevas** [comment]
@travis-jm My bad. I was doing a bit of cleaning the other day and I must have deleted my branch that had this PR by mistake. I've since restored it and have re-opened the PR!

**Comment by schickm** [comment]
For any future folks who are looking to do this, it looks like the existing attributes have been added in an importable fashion, so you just need to require them in your .eslintrc.js and then concat them onto your additions:

```
const { DEFAULT_IGNORED_PROPERTIES } = require('eslint-plugin-ember/lib/rules/avoid-leaking-state-in-ember-objects');

module.exports = {
  ...
  rules: {
    'ember/avoid-leaking-state-in-ember-objects': [2, [
      'mySweetOverride',
    ].concat(DEFAULT_IGNORED_PROPERTIES)]
  },
  ...
};

```

**Comment by cdtinney** [comment]
@bmish this can be closed
