### ISSUE TITLE
Add `no-get` rule autofixer for `getProperties`

### ISSUE THREAD

**Issue by ArtixZ** [ember-cli/eslint-plugin-ember#1821]
no-get lint rule: https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-get.md

Does this lint rule auto fix `getProperties` use cases? I'm asking because `output` in testing files are all null (code [here](https://github.com/ember-cli/eslint-plugin-ember/blob/master/tests/lib/rules/no-get.js#L319-L346)).

**Comment by bmish** [comment]
It looks like we don't autofix `getProperties` yet. Would be happy to accept an autofixer for any such cases where we can safely and practically do so.

Related: #1556

**Comment by ArtixZ** [comment]
I can probably help. But any in-advance high level advice for the layman of this repo  would be appreciated.

**Comment by bmish** [comment]
First I think you'll want to comment here to show some before/after code samples demonstrating that the autofix is possible and safe.

Then you can look into adding a `fix` property to the relevant `context.report()` calls inside the rule.

**Comment by ArtixZ** [comment]
> const { foo, bar } = getProperties(
      this.obj,
	  foo,
	  bar
    );

==>
> const foo = this.obj.foo;
const  bar = this.obj.bar;


and

> this.getProperties('prop1', 'prop2');

==>
> {prop1: this.prop1, prop2: this.prop2}


and


> this.getProperties(['prop1', 'prop2'])

==>
> {prop1: this.prop1, prop2: this.prop2}

**Comment by ArtixZ** [comment]
My code change is done. But I don't seem to have the access to push a new branch FYI.

**Comment by bmish** [comment]
You have to fork the repo to create a PR.

**Comment by ArtixZ** [comment]
I'd like to alter a little bit the expectation of the first case above:

> const { foo, bar } = getProperties(
	this.obj,
	foo,
	bar
);

==>
<s>const foo = this.obj.foo;
const bar = this.obj.bar;</s>
>const { foo, bar } = this.obj;
