### ISSUE TITLE
`ember/no-empty-glimmer-component-classes` should pass if class has generic parameter

### ISSUE THREAD

**Issue by nwhittaker** [ember-cli/eslint-plugin-ember#1822]
Per the Glint doc:

> Due to the way TypeScript works, it's not possible to have a generic signature for template-only components…If that's needed, you must create an (empty) backing class…[^1]

[^1]: https://typed-ember.gitbook.io/glint/using-glint/ember/template-only-components

**Comment by lin-ll** [comment]
If I understood this correctly, this was fixed in https://github.com/ember-cli/eslint-plugin-ember/pull/1876 🙂
