### ISSUE TITLE
Enhancement - `no-get` rule and auto-fix

### ISSUE THREAD

**Issue by ArtixZ** [ember-cli/eslint-plugin-ember#1840]
As is mentioned [here](https://github.com/ArtixZ/eslint-plugin-ember/blob/e497078f33f1423e448ede8cfc90b18d7f8f0723/tests/lib/rules/no-get.js#L56) in the test file, we currently don't identify or auto-fix `get` on a non-string. This means when the non-string is a variable name, we deem it as valid.

This ticket propose that we identify and auto-fix for those use cases. 

Expectations:

`obj.get(5)` ===> `obj[5]`   // `obj.get(5)` is legal as I tested.

`obj.get(foo)` ===> `obj[foo]`

**Comment by ArtixZ** [comment]
Incoporating the bug mentioned in #1835, here is the list of examples of new enhancements should be added:

`obj.get(5)` ===> `obj[5]` // `obj.get(5)` is legal as I tested.

`obj.get(foo)` ===> `obj[foo]`

`obj.get('firstObject')` ===> `obj[0]`

`obj.get('lastObject')` ===> `obj[obj.length - 1]`

`foo1 === foo2 ? obj.get('bar') : obj.get('baz')` ===> `foo1 === foo2 ? obj.bar : obj.baz`

**Comment by bmish** [comment]
Great, would love to autofix additional cases that we can safely fix.
