### ISSUE TITLE
ember/no-assignment-of-untracked-properties-used-in-tracking-contexts with tracked-built-ins

### ISSUE THREAD

**Issue by amk221** [ember-cli/eslint-plugin-ember#1864]
This rule is incorrectly reporting, when `tracked` is used via `tracked-built-ins`

**Comment by NullVoxPopuli** [comment]
@amk221 can you provide a code sample for where this is falling apart?

**Comment by amk221** [comment]
I would love to but it doesn't seem to be doing it any more. Happy to close
