### ISSUE TITLE
<template> tag parsing issue in templates shorter than 3 characters 

### ISSUE THREAD

**Issue by chancancode** [ember-cli/eslint-plugin-ember#1894]
1. `ember new --yarn zomg`, as of now that gives you:
   1. `ember-cli@5.0.0`
   1. `eslint@8.43.0`
   1. `eslint-plugin-ember@11.8.0`
1. Disable prettier integration (to isolate the problem to eslint):
   1. Remove `eslint-config-prettier` package
   1. Remove `eslint-plugin-prettier` package
   1. Remove `extends` `plugin:prettier/recommended`
   1. `yarn`
1. Add `app/components/foo.gjs` with the following content
1. Run `yarn lint:js` (which is `eslint . --cache`)

# 0 characters

```
export default <template></template>;
```

```
/private/tmp/zomg/app/components/foo.gjs
  0:0  error  Preprocessing error: Cannot split a chunk that has already been edited (1:13 – "</template>")

✖ 1 problem (1 error, 0 warnings)
```

# 1 character

```
export default <template>h</template>;
```

```
/private/tmp/zomg/app/components/foo.gjs
  0:0  error  Preprocessing error: Cannot overwrite across a split point

✖ 1 problem (1 error, 0 warnings)
```

# 2 characters

```
export default <template>hi</template>;
```

```
/private/tmp/zomg/app/components/foo.gjs
  0:0  error  Preprocessing error: Cannot overwrite a zero-length range – use appendLeft or prependRight instead

✖ 1 problem (1 error, 0 warnings)
```

# 3 characters

```
export default <template>hi!</template>;
```

```
✨  Done in 0.59s.
```

(The result is the same if you put the template tag inside a class body)

**Comment by bmish** [comment]
Note that this change was reverted:

* https://github.com/ember-cli/eslint-plugin-ember/pull/1920
* https://github.com/ember-cli/eslint-plugin-ember/pull/1941
