### ISSUE TITLE
New rule to lint against referencing `let` variables in `<template>`

### ISSUE THREAD

**Issue by chancancode** [ember-cli/eslint-plugin-ember#1897]
```js
// app/components/foo.gjs
let foo = 1;

function increment() {
  foo++;
}

export default <template>{{foo}}</template>;
```

This does not "work" – it doesn't _error_, but it will essentially capture and compile in the value of the `foo` variable at some arbitrary point and never update again. Even if the component is torn down and a new instance is created/rendered, it will probably still hold on to the old value when the template was initially compiled.

So, generally speaking, one should avoid referencing `let` variables from within `<template>` and instead prefer to use `const` bindings to avoid this confusion/foot-gun.

**Comment by patricklx** [comment]
Should be easy to implement with #1920
