### ISSUE TITLE
Parsing error for template tags within classes on v11.11.0

### ISSUE THREAD

**Issue by Techn1x** [ember-cli/eslint-plugin-ember#1940]
I just bumped to eslint-plugin-ember 11.11.0 which consumes this PR https://github.com/ember-cli/eslint-plugin-ember/pull/1920

However, now all of my GTS and GJS files seem to cause eslint parsing errors where they use the `<template>` tag within a class.

Within a class
> Parsing error: Unexpected token. A constructor, method, accessor, or property was expected

Within a TOC
> Parsing error: '>' expected

Here's an example component
![Screenshot 2023-08-22 at 9 24 20 pm](https://github.com/ember-cli/eslint-plugin-ember/assets/1049837/3db2857e-1c6a-4e33-901b-39ac77eb34df)

and the error
![Screenshot 2023-08-22 at 9 25 16 pm](https://github.com/ember-cli/eslint-plugin-ember/assets/1049837/28316329-51cc-495c-bdde-660ec1008909)
eslint output
![Screenshot 2023-08-22 at 9 25 46 pm](https://github.com/ember-cli/eslint-plugin-ember/assets/1049837/99f51970-cfe9-4632-b2de-75cca53c707e)

Relevant packages installed;
eslint 8.47
eslint-plugin-ember 11.11.0
ember-template-lint 5.11.2
ember-template-lint-plugin-prettier 5.0.0
prettier-plugin-ember-template-tag 1.0.2

**Comment by bmish** [comment]
As mentioned in https://github.com/ember-cli/eslint-plugin-ember/pull/1920#issuecomment-1687993470, if https://github.com/ember-cli/eslint-plugin-ember/pull/1920 is a breaking change, we will need to revert it.

**Comment by Techn1x** [comment]
After some messing around, what does fix it, is if I place the ember config after the typescript-eslint config, as well as commenting out the parser. recommended or base doesn't seem to matter for the typescript-eslint config here.

![Screenshot 2023-08-22 at 9 45 14 pm](https://github.com/ember-cli/eslint-plugin-ember/assets/1049837/130e62fe-6809-4a56-b057-42d0d6811637)

The parsing errors I mentioned go away (I just get a whole bunch of different ones, but I don't _think_ they're related)

**Comment by bmish** [comment]
We can't control what order people set their configs in or whether they use a parser globally. So it sounds like a breaking change.

@patricklx let's do a revert then. Is there another approach you'd like to try that isn't breaking? Or an acceptable breaking change that we should save for a major release?

**Comment by Techn1x** [comment]
Just FWIW: the `@typescript-eslint/base` config overrides the parser here

https://github.com/typescript-eslint/typescript-eslint/blob/5ee1dfe872f67cb504c89e95b1450a65802e11a8/packages/eslint-plugin/src/configs/base.ts#L9
