### ISSUE TITLE
Replace ember-template-imports with content-tag

### ISSUE THREAD

**Issue by gitKrystan** [ember-cli/eslint-plugin-ember#1957]
## Resources
https://github.com/embroider-build/content-tag
https://github.com/ember-template-imports/ember-template-imports/releases/tag/v4.0.0

## Considerations

It's likely that updating to `content-tag` here will break compatibility with `prettier-plugin-ember-template-tag` and vice versa. See notes here: https://github.com/gitKrystan/prettier-plugin-ember-template-tag/issues/149

**Comment by patricklx** [comment]
Hi, thats why there is work on https://github.com/ember-cli/eslint-plugin-ember/pull/1942
Where no more changes on prettier plugin are needed as it will receive the original source code.

**Comment by gitKrystan** [comment]
> Where no more changes on prettier plugin are needed as it will receive the original source code.

Thanks for the heads up! This will be a big help.
