### ISSUE TITLE
Support "Type aware" linting for gts files

### ISSUE THREAD

**Issue by vstefanovic97** [ember-cli/eslint-plugin-ember#1995]
I'm not really a pro at Eslint nor Typescript Compiler, but I did notice this strange behaviour
To me it seems that "type aware" linting isn't really fully working.

For example if we import something from a `gts` file, whatever we imported, the [@typescript-eslint/parser](https://typescript-eslint.io/packages/parser/) won't be aware of it's types

Here is a link to a fork where I setup a test with reproduction:
https://github.com/vstefanovic97/eslint-plugin-ember/commit/70235ac016b7a3361bd2fdb483c7670e3fab9319

This is my theory on why this is happening (though I might be wrong):

Right now we rely on [@typescript-eslint/parser](https://typescript-eslint.io/packages/parser/) to do everything and we just forward options to it, but if we just rely on it, it will generate a Typescript `Program` w/o including any of our `gts` files. It seems like we need to create our own typescript `Program` with a custom `CompilerHost` that will know how to read `gts` files.

For context, terminology like `Program` and `CompilerHost` are from https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API, and `typescript-eslint` supports us providing it a `program` in it's options so that seems like the way to go to me at least

**Comment by bmish** [comment]
@patricklx @NullVoxPopuli

**Comment by patricklx** [comment]
@NullVoxPopuli i remember you tried something with glint program? Maybe that would work for this?

**Comment by vstefanovic97** [comment]
@NullVoxPopuli in my reproduction, I am using `gjs-gts-parser` for the `gts` files, see [here](
https://github.com/vstefanovic97/eslint-plugin-ember/commit/70235ac016b7a3361bd2fdb483c7670e3fab9319#diff-25f04c9ea7361cc9ea80710350c44fe78b386a31e58349a86e3c819ce143149fR780).

But still there is the issue, unless I am missing something

**Comment by patricklx** [comment]
The issue is when gts is imported, not linted directly. But for typed linting the parser also needs to load the imported files. Internally tgat is done by typescript-eslint parser

**Comment by patricklx** [comment]
Maybe we need a small ts plugin for this? Like for vue 
https://github.com/sandersn/vue-ts-plugin/blob/master/lib/index.ts

**Comment by vstefanovic97** [comment]
@patricklx, @NullVoxPopuli seems like the only reason why even direct linting of a `gts` file works, is because `typescript-eslint` internally overrides the `readFile` method of it's `CompilerHost` to use the code we provide as the first argument to it's `parseForEslint` method, instead of the actual file on disk.

See https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts#L273

But unfortunatelly this means it will only treat that one file like that, and for the rest it will read from disk, which means it will try to import `gts` files which it doesn't know how to read.

Maybe asking `typescript-eslint` repo for a feature to provide an option as an argument where we could provide our own `readFile` implementation will be enough?

**Comment by vstefanovic97** [comment]
> @patricklx, @NullVoxPopuli seems like the only reason why even direct linting of a `gts` file works, is because `typescript-eslint` internally overrides the `readFile` method of it's `CompilerHost` to use the code we provide as the first argument to its `parseForEslint` method, instead of the actual file on disk.
> 
> See https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts#L273
> 
> But unfortunatelly this means it will only treat that one file like that, and for the rest it will read from disk, which means it will try to import `gts` files which it doesn't know how to read.
> 
> Maybe asking `typescript-eslint` repo for a feature to provide an option as an argument where we could provide our own `readFile` implementation will be enough?

Such feature might be beneficial not only to us, but seems like vue has same issue right now
https://github.com/vuejs/vue-eslint-parser/issues/104

**Comment by NullVoxPopuli** [comment]
If we could tell it to use glint instead of tsc of 'the program', i think that could help, as it also has its own read file ...

If it weren't for this

> internally overrides the readFile method of it's CompilerHost 

🙈

**Comment by vstefanovic97** [comment]
> If we could tell it to use glint instead of tsc of 'the program', i think that could help, as it also has its own read file ...
> 
> If it weren't for this
> 
> > internally overrides the readFile method of it's CompilerHost
> 
> 🙈

@NullVoxPopuli well if we pass it glints TS program, then it won't override anything it just uses the program as it's given

**Comment by patricklx** [comment]
Maybe we can use this?
https://github.com/typescript-eslint/typescript-eslint/blob/fadc7940b456f1903a282a4b5085daf1b8367b16/packages/parser/src/index.ts#L7
Patch it and pass it as program parser option?

**Comment by vstefanovic97** [comment]
> Glint just maybe seems a bit overkill for this, if we could just override `readFile` that `typescript-eslint` is using by asking them to provide a new option for it, we can the just use [transformForEslint](https://github.com/ember-cli/eslint-plugin-ember/blob/master/lib/parsers/gjs-gts-parser.js#L463) method as the override, it would solve the problem I think and not have us depend on glint.
> 
> But it is just a theory, I can test it out tomorrow and if it works I can raise a feature request to `typescript-eslint`. Wdyt? But in case they won't be willing to let us override it we probably will need to use glint or something

I tried a few thing, but for now I just can't seem to get it to work :(
