### ISSUE TITLE
@typescript-eslint/eslint-recommended not applicable to `*.gts` files

### ISSUE THREAD

**Issue by chancancode** [ember-cli/eslint-plugin-ember#2106]
The instructions in the README does not fully work, see: https://github.com/typescript-eslint/typescript-eslint/issues/8607

It seems like the recommended/preferred fix is to use flat config; until then, as a workaround, I just duplicated those rules (only the `@typescript-eslint/eslint-recommended` subset has this issue)

**Comment by NullVoxPopuli** [comment]
does overrides-only config work the same way? for folks with plugins that aren't yet supporting flat config?
