### ISSUE TITLE
Prefer or require use of `let` over `const`

### ISSUE THREAD

**Issue by sohara** [ember-cli/eslint-plugin-ember#215]
Like most Ember projects we prefer to use `let` over `const` for variable declarations, except for those declared at the module or file level. This approach is [summarized here](https://madhatted.com/2016/1/25/let-it-be) and seems to be adhered to by most open source Ember projects, including the Ember source code itself.

In order to make this convention easy to adhere to I think it would be great to have a eslint rule for it, possibly optional. Has this been considered for eslint-plugin-ember?

**Comment by kellyselden** [comment]
@sohara I've been using https://github.com/cowboyd/eslint-plugin-prefer-let for most my projects. Not sure if you are aware of it.

**Comment by sohara** [comment]
Thanks @kellyselden! That plugin looks to be exactly what we need. Closing this issue.
