### ISSUE TITLE
no-global-jquery rule clashes new-module-imports rule

### ISSUE THREAD

**Issue by IgorKvasn** [ember-cli/eslint-plugin-ember#222]
Hi,
I upgraded from 5.0.0 to 5.0.3 and I am getting lint errors:

` Do not use global `$` or `jQuery` (ember/no-global-jquery)`

My code looks like this:

```
import $ from 'jquery';

$(this.element).addClass('hello');
```

and when I change to code to this:
```
import Ember from 'ember;'

Ember.$(this.element).addClass('hello');
```

I am getting lint error:  `Use import $ from 'jquery'; instead of using Ember.$ (ember/new-module-imports)`

Not sure how to fix this error, because it seems that no matter what I do, there is an linting error :)

**Comment by ajcolter** [comment]
+1

**Comment by initram** [comment]
Is this still an issue using the latest version? #283 seems to believe it has been fixed in a later version.

I tried to create a failing test, but was unable to.

**Comment by rwjblue** [comment]
Thank you @initram
