### ISSUE TITLE
Make `require-super-in-init` more generic

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/eslint-plugin-ember#228]
As originally suggested in #82 IMHO it does make sense to require calling `this._super()` in all life-cycle hooks. If you don't call it that should be a deliberate decision and can be expressed by disabling the rule for that specific hook using an ESLint comment.

**Comment by rwjblue** [comment]
Completely agree. This was also recently brought up in https://github.com/emberjs/rfcs/pull/298.  Specifically, as a path to enabling deprecating the `Ember.on` usage mentioned there we need to be able to ensure that folks properly call `_super`...

**Comment by 22a** [comment]
We've implemented this behaviour in-house and would like to contribute it back to this plugin. Assuming this is something we still want here, I'll try to prep a PR next week.
