### ISSUE TITLE
eslint-plugin-ember should allow "needs" on routes and controllers

### ISSUE THREAD

**Issue by vmalloc** [ember-cli/eslint-plugin-ember#237]
For testing ember apps (in unit-test mode) controllers need to be set with `needs` class-level properties to load needed services and dependency injections. However the eslint plugin flags these as "leaking state" (`ember/avoid-leaking-state-in-ember-objects`).

I'm not aware of any way to work around this, and also trying to blacklist those warnings doesn't seem to work - I tried adding to my `.eslintrc.js`:
```
overrides: [
    // node files
    {
      files: [
        'testem.js',
        'ember-cli-build.js',
        'config/**/*.js',
        'lib/*/index.js'
      ],
      parserOptions: {
        sourceType: 'script',
        ecmaVersion: 2015
      },
      env: {
        browser: false,
        node: true
      }
    },
    {
      files: ['**/*.js'],
      rules: {
          'ember/avoid-leaking-state-in-ember-object': 'off',
      },
    },
```
But I'm still getting those errors from `ember build`...

**Comment by Turbo87** [comment]
since the new testing APIs don't need `needs` anymore I don't think we will implement/fix this
