### ISSUE TITLE
Prefer qunit-dom rule

### ISSUE THREAD

**Issue by amk221** [ember-cli/eslint-plugin-ember#244]
Proposing a new rule that prompts developers to use [qunit-dom](https://github.com/simplabs/qunit-dom) when possible.

**Comment by Turbo87** [comment]
@amk221 I think it would make sense to put that in a dedicated `eslint-plugin-qunit-dom` project since qunit-dom can also be used outside of Ember projects, but in general I like the idea. it could probably use similar rules to the codemod (https://github.com/simplabs/qunit-dom-codemod).
