### ISSUE TITLE
Rule for no-mixins?

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/eslint-plugin-ember#270]
It is possible / likely that mixins will not ever be compatible with ES classes. Would a PR for a `no-mixins` rule be considered?

**Comment by rwjblue** [comment]
tldr; yes

See https://github.com/ember-cli/eslint-plugin-ember/pull/256 for a first step (adds a rule that would flag `Mixin.create`), but there is also some conversation about a second rule that I think we need (to prevent passing multiple arguments to `.extend()`).

**Comment by alexlafroscia** [comment]
Should this be closed, now that we have the `no-new-mixins` rule?
