### ISSUE TITLE
Deprecation of experimentalObjectRestSpread

### ISSUE THREAD

**Issue by josemarluedke** [ember-cli/eslint-plugin-ember#271]
I'm getting this deprecation warning when using the latest eslint `5.1.0` in my project in combination with this `eslint-plugin-ember`.

```(node:4020) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "node_modules/eslint-plugin-ember/lib/config/base.js")```

**Comment by rwjblue** [comment]
Related to https://github.com/ember-cli/eslint-plugin-ember/pull/267

**Comment by bmish** [comment]
Fixed by #267.
