### ISSUE TITLE
Extends `require-super-in-init` to all lifecycle hooks

### ISSUE THREAD

**Issue by cbou** [ember-cli/eslint-plugin-ember#275]
I had an issue on a project because I forgot to add `this._super(...arguments);` in the willDestroyElement hook.

I think it would make sense to extend the rule `require-super-in-init` to all lifecycle hooks.

**Comment by Alonski** [comment]
Just mentioning that this seems to be a duplicate of #228

**Comment by bmish** [comment]
Closing as duplicate of #228.
