### ISSUE TITLE
Error on unwrapBraceExpressions

### ISSUE THREAD

**Issue by roodie-ree** [ember-cli/eslint-plugin-ember#286]
I get errors on some files where apparently some elements in the `dependentKeys `array passed into `unwrapBraceExpressions `are not strings and thus have no match method. I did log the value and it was this regular expression object: `/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)\S{8,}/`. 

The check at the start of the loop does not catch this, since
` /{.+}/g.test(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)\S{8,}/) === true`

You should just add check that the type of key really is string.

**Comment by Turbo87** [comment]
can you provide a failing test case?

**Comment by roodie-ree** [comment]
Sure, test rule 'use-brace-expansion' with `{ code: '{ test: computed.match("email", /^.+@.+/)' },`

**Comment by rwjblue** [comment]
Closed by https://github.com/ember-cli/eslint-plugin-ember/pull/299
