### ISSUE TITLE
Cannot find new rule definitions from 5.3.0

### ISSUE THREAD

**Issue by gmurphey** [ember-cli/eslint-plugin-ember#313]
Attempted to enable the following new rules:

- `ember/no-restricted-resolver-tests`
- `ember/no-new-mixins`
- `ember/no-test-import-export`

But they don't seem to be defined in `lib/index.js`. Happy to take care of this tomorrow if no one beats me to it.

**Comment by rwjblue** [comment]
:weary: sorry about that! Definitely appreciate a PR for this.
