### ISSUE TITLE
Cannot read property 'arguments' of null with no-restricted-resolver-tests

### ISSUE THREAD

**Issue by amk221** [ember-cli/eslint-plugin-ember#337]
Getting this after upgrading to 6.0.0

Setting `ember/no-restricted-resolver-tests': 'off'` fixes it

**Comment by gmurphey** [comment]
Seems to fail with the following code:

```
import { setupTest } from 'ember-qunit';

module('foo', function(hooks) {
  setupTest(hooks);
});
```

`setupTest` in the import statement is run through the rule.

**Comment by Turbo87** [comment]
@scalvert do you have time to take a look at this?
