### ISSUE TITLE
Question: why isn't 'no-ember-super-in-es-classes' enabled in recommended config?

### ISSUE THREAD

**Issue by jacobq** [ember-cli/eslint-plugin-ember#414]
Is there ever a case where calling `this._super` in an ES6 class method produces the desired behavior while `super.methodName` does not? I would've thought that this rule should be enabled by default as this is very easy to accidentally mess-up while migrating to use of native classes.

[`no-ember-super-in-es-classes`](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-ember-super-in-es-classes.md)

https://github.com/ember-cli/eslint-plugin-ember/blob/704057598335a2b216bfcaa9e63eab8374bcafc9/lib/recommended-rules.js#L22

**Comment by rwjblue** [comment]
IMHO, it should be. It will be a "breaking bugfix" but the code in question _is **already** broken_.

**Comment by bmish** [comment]
@rwjblue how often do you think we should have major version releases where we can turn on more recommended rules?
