### ISSUE TITLE
Rule `require-computed-property-dependencies` doesn't recognize all braced dependent keys

### ISSUE THREAD

**Issue by kimroen** [ember-cli/eslint-plugin-ember#470]
It looks like the new rule introduced in https://github.com/ember-cli/eslint-plugin-ember/pull/458 doesn't recognize dependent keys in this format: `"article.{comments.[],title}"`. That is, a dependent key with an array inside braces.

With this, I get the linting error saying that `article.title` isn't in the dependent keys.

Specifying them separately works (`"article.title", "article.comments.[]"`), but that triggers the other rule regarding duplicate dependent keys.

A workaround is putting the key with an array last. This version works: `"article.{title,comments.[]}"`.

**Comment by bmish** [comment]
Thanks for reporting! This should be mostly fixed in v6.9.1.
