### ISSUE TITLE
New rule proposal "no-attrs-snapshot"

### ISSUE THREAD

**Issue by michalsnik** [ember-cli/eslint-plugin-ember#51]
Import `no-attrs-snapshot` from @chadhietala's https://github.com/ember-best-practices/eslint-plugin-ember-best-practices/blob/master/guides/rules/no-attrs-snapshot.md

**Comment by scalvert** [comment]
I've picked this issue up. PR forthcoming.

**Comment by michalsnik** [comment]
Released in `v4.0.0`. I had to bump major version as it's the recommended rule and it might break the build after updating.
