### ISSUE TITLE
Introduce an `octane` configuration

### ISSUE THREAD

**Issue by patocallaghan** [ember-cli/eslint-plugin-ember#533]
Recently ember-cli-template introduced an `octane` configuration which guides users to use new Octane patterns over classic component patterns.

https://github.com/ember-template-lint/ember-template-lint/blob/e10fed889cb6a17fd4d3cffbaa17fbbbbd46e813/lib/config/octane.js

We should introduce the same here for eslint-plugin-ember. I'd be happy to put together a PR introducing the config but we should figure out:

1) What rules should be included in the config
2) What rules are we currently missing?

**Comment by rwjblue** [comment]
Some possible ideas:

* disallow using `actions` hash (favoring instead, `@action` or `foo: action(function() {})`)
* disallow "classic" classes (preferring native class)

@chancancode / @pzuraq / @Turbo87 / @bmish - Thoughts?

**Comment by Turbo87** [comment]
- disallow `didInsertElement/willDestroyElement()` (in favor of `@ember/render-modifiers`)
- `only-tagless-components` (allows `@glimmer/component` base class, or `tagName: ''` if `@ember/component`)
- disallow `@ember/component` base class
- enforce component colocation

not sure if any of them should be enabled by default for the `octane` ruleset though. 🤔

**Comment by pzuraq** [comment]
> disallow didInsertElement/willDestroyElement() (in favor of @ember/render-modifiers)

I think we should recommend modifiers in general, not just `@ember/render-modifiers`, but otherwise I think that's a goo didea

**Comment by patocallaghan** [comment]
So collating this list from the above comments we have:

* disallow using `actions` hash (favoring instead, `@action` or `foo: action(function() {}))`
* disallow "classic" classes (preferring native class)
* disallow `didInsertElement/willDestroyElement()` (in favor of modifiers in general)
* `only-tagless-components` (allows `@glimmer/component` base class, or `tagName: ''` if `@ember/component`)
* disallow `@ember/component` base class
* enforce component colocation

Two I was thinking of were:

* "no computed properties in native classes", i.e. always use `@tracked`
* Similar to the `only-tagless-components` idea above but instead being no classic components at all

I guess if there is agreement that all of these rules are useful I could create issues for each of them and myself and possibly others could work through the list. Then at the end figure out what needs to go into the actual `octane` config file.

**Comment by Alonski** [comment]
Maybe another rule for `no computed`
Which means that `computed` and all its variants such as `readOnly/alias` etc can't be used?

**Comment by patocallaghan** [comment]
@Alonski I mention the following above

> "no computed properties in native classes", i.e. always use @tracked

Is that the same as what you meant?

**Comment by Alonski** [comment]
Oh yes @patocallaghan Sorry I missed it. It also includes the functions under the computed name space?

**Comment by patocallaghan** [comment]
Yep it should 🎉 thanks

**Comment by patocallaghan** [comment]
I've cut issues for all the various lint rules proposed here. We can use this issue to track what actually goes into the Octane config as I don't think all should.

If someone could label the issues `help wanted` that would be great as I might reach out to the Ember Times team to see if we can broadcast we need the help building these.

**Comment by rwjblue** [comment]
> If someone could label the issues help wanted that would be great

Done!
