### ISSUE TITLE
Update existing rules to handle native classes

### ISSUE THREAD

**Issue by bmish** [ember-cli/eslint-plugin-ember#560]
For example, `no-new-mixins` presumably should apply to both classic/native classes.

This would be good preparation for Ember Octane.

_Originally posted by @bmish in https://github.com/ember-cli/eslint-plugin-ember/pull/558#issuecomment-547232645_

Related to #566.

**Comment by laurmurclar** [comment]
The `order-in-*` rules were already called out: https://github.com/ember-cli/eslint-plugin-ember/issues/417

I can start fixing those today

**Comment by bmish** [comment]
@laurmurclar that would be great, thanks! I was looking at the code for those rules and it looks like it should be quick to update them. If we can get that change in today then I'll include it in a new release today.

**Comment by laurmurclar** [comment]
@bmish Afraid it wont be today! But feel free to work away at them if you have time

**Comment by bmish** [comment]
I'm going to close this. At this point, most rules have been updated with support for native JavaScript classes and decorators, including the most important ones. The few remaining rules that haven't been updated note "Missing native JavaScript class support" in their rule docs.
