### ISSUE TITLE
New Rule: `no-string-prototype-extensions`

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/eslint-plugin-ember#638]
This new rule would look at method invocations with the names mentioned on https://api.emberjs.com/ember/3.11/classes/String. It could potentially also have an option to only trigger on static strings, but I'm not sure how useful that would be 🤔

**Comment by cdtinney** [comment]
This could be written similar to https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-function-prototype-extensions.md

**Comment by sdahlbac** [comment]
I could have a go at this one

**Comment by sdahlbac** [comment]
Flagging the incorrect uses seems straightforward, but what would we suggest as the correct thing to do?
