### ISSUE TITLE
New Rule: Catch duplicate @attr in native classes

### ISSUE THREAD

**Issue by abhilashlr** [ember-cli/eslint-plugin-ember#668]
Before:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/5667722/74301223-6db1bb00-4d78-11ea-8e28-03e38c96dea4.png">

After:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/5667722/74301246-7e623100-4d78-11ea-8837-dcbd4ac94881.png">

The errors on duplicate keys don't seem to fire.

Similar to errors from [no-dupe-keys](https://eslint.org/docs/rules/no-dupe-keys).

**Comment by jaydgruber** [comment]
would a more general rule `no-duplicate-class-properties` make sense here?

**Comment by Turbo87** [comment]
> would a more general rule `no-duplicate-class-properties` make sense here?

yes, see https://github.com/babel/eslint-plugin-babel/pull/191 😉 

it doesn't belong in eslint-plugin-ember though, since it's a generic rule and not specific to Ember.js
