### ISSUE TITLE
New Rule: Use ember test-helper util function in tests instead of native window method

### ISSUE THREAD

**Issue by fierysunset** [ember-cli/eslint-plugin-ember#676]
ID: `prefer-ember-test-helpers`

**Overview:**
We would like to add a lint rule to assist in users writing tests in Ember using `@ember/test-helpers` to ensure they are using the correct method, in particular with async calls.

A complete list of Window native methods are here: https://developer.mozilla.org/en-US/docs/Web/API/Window#Methods
These are the methods in ember-test-helpers (notably the DOM related sections): https://github.com/emberjs/ember-test-helpers/blob/master/API.md

This is the list we've identified already that have overlap, please call out others if missing :)
- blur
- find
- focus

**Background:**
In writing tests I discovered that a `focus()` call was being made without an import from `@ember/test-helpers`. This meant that it was actually the native `focus()` method on `window` being used, so trying to `await` did not have the right behavior, nor were there any errors or warnings thrown since it's a legitimate native method call.

**Comment by rwjblue** [comment]
@fierysunset - Seems generally good to me.

@bmish / @Turbo87 - Thoughts?

**Comment by Turbo87** [comment]
yep, sounds good to me 👍 

@kellyselden did we discuss this at some point? the proposal seems somehow familiar 🤔

**Comment by kellyselden** [comment]
@Turbo87 indeed:

https://github.com/ember-cli/ember-cli/pull/7858
https://github.com/ember-cli/eslint-plugin-ember/pull/258

**Comment by fierysunset** [comment]
Ah! Thanks for the link, @kellyselden :) 

So an error for using `find` into `ember-cli` - how would you guys like us to proceed?

**Comment by bmish** [comment]
The new rule could be called `prefer-ember-test-helpers`? It would flag calls from `window` such as `blur()` / `window.blur()` / etc that overlap with functions in @ember/test-helpers and are not imported from @ember/test-helpers. We have a helper `emberUtils.isTestFile()` to ensure the lint rule only runs on tests.

**Comment by fierysunset** [comment]
That sounds good to me - would this be a brand new rule that should exist entirely separately of the earlier rule that @kellyselden called out?

**Comment by bmish** [comment]
I believe we only need one new rule since the issues are talking about the same thing.

**Comment by fierysunset** [comment]
Should we get rid of the old one or just keep it intact?

**Comment by bmish** [comment]
We can proceed with this issue, I closed #258.

**Comment by fierysunset** [comment]
Sounds good! I'll find some time in the next week to work on it and get back to you all. Thanks for the responses! <3
