### ISSUE TITLE
New Rule: no-legacy-test-waiters

### ISSUE THREAD

**Issue by scalvert** [ember-cli/eslint-plugin-ember#680]
As part of the rollout of [RFC 581](https://github.com/emberjs/rfcs/blob/master/text/0581-new-test-waiters.md), we're proposing adding this new rule to instruct consumers to migrate to the new test waiters addon. Details as to the reasoning behind migrating to the new addon can be found within the RFC.

**Comment by rwjblue** [comment]
👯‍♂️🕺💃
