### ISSUE TITLE
New rule: catching case-sensitivity errors for `isFastBoot` property

### ISSUE THREAD

**Issue by mehulkar** [ember-cli/eslint-plugin-ember#690]
It would be nice to have a lint rule to catch usages of `fastboot.isFastboot`, it should be `this.fastboot.isFastBoot` (capital Boot).

**Comment by bmish** [comment]
Two concerns with this:
1. There could be spelling/case-sensitivity mistakes in any of hundreds of properties used in an Ember application, and I'm not sure this one is particularly special.
2. We have generally avoided including rules targeting third-party addons.

I would however recommend installing a great VSCode extension (or CLI tool) called [Code Spell Checker / cspell](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) which would catch issues like this.

**Comment by mehulkar** [comment]
mostly agree on both counts. We should just have had tests that showed how the feature was broken, but we don't have any infrastructure for that at the moment. I'm fine to just close this.
