### ISSUE TITLE
Violations reported when trying to create an observer on init

### ISSUE THREAD

**Issue by MatthewPringle** [ember-cli/eslint-plugin-ember#706]
I have just finished updating my observers to remove `.on( 'init' )` as this was the documented way of firing observers on init.

I have now updated to the new recommended way of firing an observer

`myobserver: on( 'init' , observer( 'active' , function() {} )`

And now I get this warning "no-on-calls-in-components"

What gives?

**Comment by bmish** [comment]
I don't think there's a fully-compliant way to use an observer-on-init in a component anymore. Observers are pretty much deprecated at this point, so I would just disable the lint rules for the ones you still need.

Relevant rules:
* [no-observers](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-observers.md)
* [no-on-calls-in-components](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-on-calls-in-components.md)
* [no-function-prototype-extensions](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-function-prototype-extensions.md)
