### ISSUE TITLE
Small improvement to Contirbution Guide

### ISSUE THREAD

**Issue by TheMBTH** [ember-cli/eslint-plugin-ember#710]
I struggled for my first PR to this project:
- I created my rule before using generator-eslint, so I did not notice that some files needed to be updated
- This file is not documented 'tests/__snapshots__/recommended.js.snap'
-  I would like to specify to run the linter (`yarn lint` or `npm run lint:js`) and ultimately to check travis.yml for the build's steps. This will avoid failed build
- I would like to add this script to package.json:
`"format:js": "./node_modules/.bin/prettier --write 'lib/**/*.js' 'tests/**/*.js'"`

**Comment by bmish** [comment]
It's a good idea for us to improve the documentation for creating a new rule. I will work on this too.

A few notes:

1. New rules should not be added as recommended.
2. `yarn lint` and `yarn test` can be run locally to check most things.
3. `yarn lint:js --fix` is the right way to autofix formatting.

**Comment by TheMBTH** [comment]
Thanks @bmish . I updated my PR according to your recommendation.

> 1. New rules should not be added as recommended.

What's the recommended way to add a rule then ?

**Comment by bmish** [comment]
We consider additional rules to be enabled as `recommended` in each major release.
