### ISSUE TITLE
Prevent "bad" router usages

### ISSUE THREAD

**Issue by mehulkar** [ember-cli/eslint-plugin-ember#762]
I noticed some usage of `.lookup('router:main')` in our apps that I factored away. not sure if it's possible, but would be nice to have a lint rule against this. Also against `router._routerMicroLib` maybe?

**Comment by bmish** [comment]
Perhaps we should expand the [no-private-routing-service](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-private-routing-service.md) rule to catch these too? CC: @nlfurniss

**Comment by rwjblue** [comment]
Ya that seems good to me.
