### ISSUE TITLE
Can't fix "Import the `find()` method from @ember/test-helpers"

### ISSUE THREAD

**Issue by pfernandom** [ember-cli/eslint-plugin-ember#811]
Hello! I'm using `"eslint-plugin-ember": "^8.4.0",` and when I use the helper `find` in my tests, O keep getting `Import the 'find()' method from @ember/test-helpers`.

No matter what I do, I cannot get rid of that error.

Here is my `.eslintrc.js`:
 ```js
module.exports = {
  root: true,
  parser: 'babel-eslint',
  env: {
    es6: true,
  },
  extends: ['plugin:ember/recommended'],
  globals: {
    generateRumSession: true,
    window: 'readonly',
    document: 'readonly',
  },
  rules: {
    'class-methods-use-this': 'warn',
    'func-names': 'off',
    'consistent-return': 'warn',
    'default-case': 'warn',
    'spaced-comment': 'warn',
    'no-unused-vars': 'error',
    eqeqeq: 'warn',
    'prefer-const': 'warn',
    'no-shadow': 'warn',
    'no-bitwise': 'warn',
    'ember/new-module-imports': 'warn',
    'ember-best-practices/no-send-action': 'warn',
    'no-trailing-spaces': 'error',
    'prefer-destructuring': 'warn',
    'no-else-return': 'off',
    'no-restricted-imports': 'warn',
    'no-undef': 'error',
    'ember/prefer-ember-test-helpers': 'error',
    'ember/no-mixins': 'warn',
  },
  parserOptions: {
    sourceType: 'module',
  },
  plugins: ['babel', 'ember'],
};

```

**Comment by GabrielCousin** [comment]
:wave:
I think it would help to share this feedback with you.
We experienced the same error but only when the import in on several lines:

```
// Throws
import {
  ...,
  find
} from '@ember/test-helpers';

// OK
import { find } from  '@ember/test-helpers';
```

**Comment by bmish** [comment]
@pfernandom It sounds like you're hitting the [prefer-ember-test-helpers](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/prefer-ember-test-helpers.md) rule in your tests that use the Ember `find` global test helper mentioned in this [doc](https://guides.emberjs.com/v2.14.0/testing/acceptance/).

> find(selector, context)
Finds an element within the app's root element and within the context (optional). Scoping to the root element is especially useful to avoid conflicts with the test framework's reporter, and this is done by default if the context is not specified.

I actually have a lot of tests that use this `find` test helper too so I currently can't enable the `prefer-ember-test-helpers` rule. Perhaps we should add an `ignoreFind` option to the rule for consumers who still use this global `find` test helper. CC: @fierysunset

@GabrielCousin could you provide a failing test case? I haven't been able to reproduce your issue (assuming it's a different issue from the first).

**Comment by GabrielCousin** [comment]
Sure, there you go!
We are currently using `eslint-plugin-ember@^8.5.0:` with `eslint@^6.8.0`
Let me know if you need any further help :)

```
import { module, test } from 'qunit';
import { setupRenderingTest } from 'ember-qunit';
import {
  render,
  find,
  click,
  findAll,
  fillIn,
  triggerEvent
} from '@ember/test-helpers';
import hbs from 'htmlbars-inline-precompile';

module('Integration | Component | search', function (hooks) {
  setupRenderingTest(hooks);

  test('it renders a default placeholder', async function (assert) {
    assert.expect(1);
    await render(hbs`<Search />`);

    assert.strictEqual(find('[data-test-input]').getAttribute('placeholder'), 'Search…');
  });
});
```

**Comment by pfernandom** [comment]
@GabrielCousin my issue is consistent with the condition you described. I also need to have the import in multiple lines.

@bmish I actually enabled `prefer-ember-test-helpers` with the idea of helping me migrate the `find` helper to use `import`. My problem happens that, even after I fix it by adding the import for `find`, I still get the error from eslint.

**Comment by rwjblue** [comment]
The import being multiple lines really shouldn't cause a material change to the way the rule works, maybe you could send a quick pull request with a failing test case?

**Comment by pfernandom** [comment]
After playing with this repo for a bit, I think that the rule breaks when there are more imports after `import { find } from '@ember/test-helpers'`.

I added this test case to `prefer-ember-test-helpers` and the rule fails:

```js
{
      filename: TEST_FILE_NAME,
      code: `import { find } from '@ember/test-helpers';
      import foo from 'bar';

      test('foo', async (assert) => {
        await find('.some-element');
      });`,
},
```

**Comment by bmish** [comment]
Yeah it's related to having multiple imports. I'm working on a fix for it now.
