### ISSUE TITLE
New rule proposal: ensure this._super() is called in lifecycle hooks

### ISSUE THREAD

**Issue by Dhaulagiri** [ember-cli/eslint-plugin-ember#82]
It is generally a good practice to call `this._super(...arguments)` in Ember's lifecycle hooks, so this rule would enforce its existence.  For setup hooks it would enforce it being the first thing called, and in teardown hooks it would enforce it being the last thing called.

**Comment by bardzusny** [comment]
1. This is not something that is always done, for all lifecycle hooks. Sometimes it can be omitted on purpose, i.e. `beforeModel` hook transitioning to other route and not calling `this._super(...)` at all. We would probably have to white/blacklist selected lifecycle hooks.
2. Some hooks already have explicit deprecation warnings when `._super` call is not present (i.e. `init()`).
3. Order is quite another question - this would have to be investigated quite thoroughly. I can see valid cases for calling `._super` both at the beginning, as well end of an override.

Overall: interesting idea, but something that would have to be discussed quite thoroughly before implementation to be actually useful (mostly worried about too many false positives, but not only this).

I think we can start with most basic proposal, then try to find false positives/annoying cases, finally see whether we can see solutions for handling them gracefully. WDYT?

**Comment by michalsnik** [comment]
Makes sense @bardzusny I think we should implement for now only the 2nd point and warn about no  `super` calls in `init` methods. Like https://github.com/ember-best-practices/eslint-plugin-ember-best-practices/blob/master/guides/rules/no-broken-super-chain.md
