### ISSUE TITLE
no-ember-super-in-es-classes lint rule's message should include the correct syntax

### ISSUE THREAD

**Issue by GoygovRustam** [ember-cli/eslint-plugin-ember#822]
Currently no-ember-super-in-es-classes lint rule's message is : **Don't use `this._super` in ES classes**

Suggested new message for educational purposes: **Don't use `this._super` in ES classes; instead, you should use super()**

**Comment by bmish** [comment]
Sounds like a good improvement to me!

**Comment by rwjblue** [comment]
FWIW, it should also be possible to support a `--fix` for this (if we don't already).
