### ISSUE TITLE
Support member functions

### ISSUE THREAD

**Issue by amk221** [ember-cli/eslint-plugin-ember#83]
With the following...

```javascript
foo: computed(function() {

}).volatile(),

bar: computed(function() {

})
```

I get `the 'bar' multi-line function should be above 'foo' method`, but I wasn't expecting to.

**Comment by michalsnik** [comment]
Ok, I didn't think about that case before. I agree this should be treated equally and not throw any error. Thanks for posting this issue @amk221 :)
