### ISSUE TITLE
support optional chaining for ember/no-get

### ISSUE THREAD

**Issue by fivetanley** [ember-cli/eslint-plugin-ember#843]
Sometimes, the autofixer can't fix stuff like:

`this.get('account.id')` Because `account` might be null. Maybe allowing an option to this plugin (until the optional chaining babel plugin becomes standard in most projects) would allow this rule to be autofixable?

Before: 

`this.get('account.id')`

After:

`this.account?.id`

Would be happy to submit a PR for this if the maintainers think it's a good idea. [Optional chaining](https://github.com/tc39/proposal-optional-chaining) is currently stage 4 in the TC39 process so this seems like a fairly stable addition to me.

**Comment by bmish** [comment]
I like the idea. Perhaps behind a `useOptionalChaining` option (default false).
