### ISSUE TITLE
possible false flagging of require-computed-property-dependencies

### ISSUE THREAD

**Issue by mcfiredrill** [ember-cli/eslint-plugin-ember#844]
I'm seeing some instances of `require-computed-property-dependencies` that look a bit strange.
Notice here that while yes, I'm using `imgRegex` in the getter, its not a value I expect to actually change. So I'm not sure why it would need to be a dependency.
https://github.com/datafruits/datafruits/pull/442/files#file-app-components-chat-message-js-L10

Is my use of `@computed` with a getter valid? These are some old components that I haven't converted to use `@tracked` yet.

```js
export default class Application extends ActiveModelAdapter.extend(FastbootAdapter) {
  imgRegex = /https?:\/\/(?:[a-z0-9-]+\.)+[a-z]{2,6}(?:\/[^/#?]+)+\.(?:jpg|gif|png|webp)(\?.*$)*/;

  @computed('message.body')
  get hasImage() {
    return this.imgRegex.test(this.message.body);
  }
}
```

**Comment by bmish** [comment]
This looks like correct behavior to me.

* There's no way for the lint rule to know that `imgRegex` won't change.
* It doesn't hurt to include it as a dependent key.
* It's good for consistency that we list out all dependent keys like this, without having to make judgment calls about which ones are expected to change or not.
