### ISSUE TITLE
[Bug] `no-computed-properties-in-native-classes` default config value is not set properly

### ISSUE THREAD

**Issue by jaydgruber** [ember-cli/eslint-plugin-ember#849]
I think I missed a trick on https://github.com/ember-cli/eslint-plugin-ember/pull/826.
(on 8.7.0) It works fine if I pass in the config value, but the `ignoreClassic: true`, default value is not being respected by the rule.

I assumed that by setting a default value in the schema: https://github.com/ember-cli/eslint-plugin-ember/blob/master/lib/rules/no-computed-properties-in-native-classes.js#L47
that some magic was happening under the hood when I accessed the config. I guess I assumed that when I was getting `context.options[0]`, what i was really accessing was a deepMerge of the user-specified-configs & the default configs, with the former taking precedence.

But now that I look at other examples in the codebase, it seems like I should provide the default value again when accessed. Almost all of the config values I see have `default: false`, so there's not really a good example.

I think just adding a trailing `|| true` at https://github.com/ember-cli/eslint-plugin-ember/blob/master/lib/rules/no-computed-properties-in-native-classes.js#L56 will fix this

**Comment by bmish** [comment]
That sounds right. You can also add a test case with no config to ensure that the option is enabled still. Want to open up a fix?

**Comment by jaydgruber** [comment]
yeah, just in the middle of something involved atm, so wrote this as notes when I ran across it.
