### ISSUE TITLE
no-observers rule triggers on variable named `observer`

### ISSUE THREAD

**Issue by nickschot** [ember-cli/eslint-plugin-ember#859]
The below seems like a false positive for this rule.

![image](https://user-images.githubusercontent.com/334789/85001443-f6d86480-b153-11ea-918a-e9c8bb557fba.png)

**Comment by rwjblue** [comment]
Yeah, this is a bug. We have an issue that was tracking making all of these rules follow the imports (instead of making assumptions on the name of the local variable). I think that is the right path forward here...
