### ISSUE TITLE
Import rules from "eslint-plugin-ember-best-practices"

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/eslint-plugin-ember#88]
It seems that the folks at LinkedIn started yet another ESLint plugin for Ember at https://github.com/ember-best-practices/eslint-plugin-ember-best-practices

IMHO we should focus our efforts on *one* plugin and `eslint-plugin-ember` seems to be the best fit for that. 

I would like to propose to 

1) import the rules from the other project
2) move this project into an independent GitHub org so that the people working on the other project can also act as maintainers here

/cc @michalsnik @trentmwillis @scalvert @rwjblue

**Comment by rwjblue** [comment]
@Turbo87 https://github.com/ember-best-practices/eslint-plugin-ember-best-practices was not started due to NIH (and the org itself has nothing to do with LinkedIn), that type of verbiage is detrimental to the goals of the type of unification that you are proposing here.

**Comment by Turbo87** [comment]
@rwjblue sorry, didn't mean to offend anyone

**Comment by michalsnik** [comment]
Hey guys! I'm all for full cooperation, but just so you know I was already talking about this with Chad and we agreed that it's good idea to merge some of the rules from eslint-plugin-ember-best-practices here. I even created issues in which I'm pointing which rule should be ported. You should check them out :) I only didn't have enough time to work on them.. But we're going to port them at the begining of the next week :)

And in terms of moving this repository to another organization we were also speaking about this with @rwjblue and we postponed that action point. We can talk more about this matter on EmberCamp!

**Comment by scalvert** [comment]
The https://github.com/ember-best-practices/eslint-plugin-ember-best-practices repo was initially created internally in LinkedIn, but quickly became apparent that the rules could be leveraged by others in the community. I know discussions started a while ago about merging the two, and my preference would be to absolutely merge and collaborate going forward.

**Comment by michalsnik** [comment]
I'm glad we're on the same page here. I'll be happy to add some of you guys @scalvert as collaborators so we can work on this process more effectively.

**Comment by scalvert** [comment]
👍

**Comment by michalsnik** [comment]
@scalvert I'd say let's try to import first rule of yours here and if our utility functions are not enough we can add additional ones or improve them. We have quite extensive test suite so we should be able to catch any issues up front :) Let's start with simple `no-attrs-snapshot` (#51). `get` utility seems like a good one to add in this repo too. And about anything else - we use structure defined by    https://github.com/eslint/generator-eslint Btw. I recently worked on unifying rules meta data in order to be able to automatically generate recommended config and table with rules in README, you might want to take a look at this too #92

**Comment by scalvert** [comment]
Sounds good. I'll start with that, adhering to this structure.

**Comment by michalsnik** [comment]
@scalvert please take a look if there is anything left to add, but I think we're good now. Some of the rules we already had, but under different names. If you'll have any anything to add please create separate issue per each idea :)
