### ISSUE TITLE
no-test-import-export rule should allowed importing from tests/helpers folder

### ISSUE THREAD

**Issue by raido** [ember-cli/eslint-plugin-ember#889]
I have hit use case where I have couple of helpers, like `tests/helpers/setup-application-test.js` which wrap default `setupApplicationTest` for additional setup.

Now with this rule all my helpers get triggered for lint error. For now I renamed the files but this seems inconvenient and also explicitly updating `eslintrc.js` to turn off this rule for just tests/helpers seems incorrect.

https://github.com/ember-cli/eslint-plugin-ember/blob/0183d453c22dcd42ce847332bdf12b91ce208c78/lib/rules/no-test-import-export.js#L45

**Comment by rwjblue** [comment]
Ya, agree. Also https://github.com/emberjs/rfcs/pull/637 will explicitly be having folks import from `my-app/tests/helpers` (using `tests/helpers/index.js` for some reexports) in all generated tests. The RFC is in FCP, and will likely land soon...

**Comment by raido** [comment]
Not sure this is fixed for relative path imports, see comment: https://github.com/ember-cli/eslint-plugin-ember/pull/895#pullrequestreview-465798175

**Comment by bmish** [comment]
Follow-up fix: https://github.com/ember-cli/eslint-plugin-ember/pull/911
