### ISSUE TITLE
New Rule: `no-controller-access-in-routes`

### ISSUE THREAD

**Issue by emonroy** [ember-cli/eslint-plugin-ember#896]
Accessing a controller by any means other than `controllerFor` (eg `get(this, 'controller')`) doesn't guarantee it to be eagerly loaded.

We're proposing adding this rule to require the use of `controllerFor` when getting a controller, preventing it from being `undefined`.

**Comment by rwjblue** [comment]
Just to confirm, you mean for this to apply to route instances specifically? In general, folks should avoid accessing the controller from their routes outside of `setupController`/`resetController` hooks (where they are passed as an argument). 🤔

**Comment by emonroy** [comment]
Hi @rwjblue, yes, since `controllerFor` is a member of Router class it would apply to route instances.

We have cases where we want to access the controller from methods other than `setupController`/`resetController` (eg an action in the route that updates a property in the controller for the route template).

**Comment by rwjblue** [comment]
> We have cases where we want to access the controller from methods other than setupController/resetController (eg an action in the route that updates a property in the controller for the route template).

Sure, but in general that route template's _default_ target **is** the controller (and to bubble up to the route you have to implement an action in _both_ places!?!).

**Comment by emonroy** [comment]
You're right, for a simple use case the action could be implemented in the controller as it's the template's default target.

However, in more complex use cases (eg sub-routes with controller actions invoking `send`) you could need to access the controller from the action.

Let me know if you want a more concrete example of accessing the controller from a route action.

**Comment by rwjblue** [comment]
> Let me know if you want a more concrete example of accessing the controller from a route action.

No no, sorry I wasn't arguing with you RE: the rule. I just think we should _probably_ have the rule be `no-controller-access-in-routes`, then have that rule take an option like `allowControllerFor`. I think that would give you want you intend, but also (by default) guide folks away from reaching into the controller from a route...

**Comment by emonroy** [comment]
Sounds good, I can rename the rule to `no-controller-access-in-routes`, thanks @rwjblue .

Just out of curiosity, if accessing the controller from outside of `setupController`/`resetController` is discouraged, why do we have `controllerFor`?
