### ISSUE TITLE
`no-side-effects` rule false positive with closure

### ISSUE THREAD

**Issue by bmish** [ember-cli/eslint-plugin-ember#915]
"Another false positive:

~~~js
computed(function () {
  return foo => this.set('val', foo);
})
~~~

Or am I missing something? This is a closure, and thus not a side effect..."

_Originally posted by @franzliedke in https://github.com/ember-cli/eslint-plugin-ember/issues/351#issuecomment-509590491_

**Comment by bmish** [comment]
Closing due to lack of interest and closures not being a great heuristic.

**Comment by franzliedke** [comment]
Does that mean closures will be ignored?
