### ISSUE TITLE
no-actions-hash fails on class extensions that contain `...`

### ISSUE THREAD

**Issue by carakessler** [ember-cli/eslint-plugin-ember#921]
Error thrown: `Cannot read property 'name' of undefined` 

How to trigger: 
```
Service.extend({
   ...foo,
})
```

Anything with the spread operator inside a class extension causes a error to be thrown

**Comment by bmish** [comment]
I haven't been able to reproduce this bug. Have you tested with the latest version of eslint-plugin-ember? If so, can you try adding a failing test case?

**Comment by carakessler** [comment]
Bumped to latest, and still see the error running `ember/no-actions-hash`

Here is my config:
```
const OCTANE_ES_LINT_CONFIG: ESLintOptions = {
  parser: 'babel-eslint',
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
    ecmaFeatures: {
      legacyDecorators: true,
    },
  },
  plugins: ['ember'],
  envs: ['browser'],
  rules: {
    'ember/classic-decorator-hooks': 'error',
    'ember/classic-decorator-no-classic-methods': 'error',
    'ember/no-actions-hash': 'error',
    'ember/no-classic-classes': 'error',
    'ember/no-classic-components': 'error',
    'ember/no-component-lifecycle-hooks': 'error',
    'ember/no-computed-properties-in-native-classes': 'error',
    'ember/no-get-with-default': 'error',
    'ember/no-get': 'error',
    'ember/no-jquery': 'error',
    'ember/require-tagless-components': 'error',
    'ember/no-mixins': 'error',
  },
  useEslintrc: false,
};
``` 
Confirmed that it works when `ember/no-actions-hash` is removed from config. 

Here is a failing test case: 
```
      this.owner.register(
        'service:deprecated-main-nav@main-nav',
        Service.extend(Evented, {
          ...this.badge,
          getBadgeCount: this.sandbox.stub().returns(4),
        })
      );
```

**Comment by bmish** [comment]
Hmm this is odd. I tested again and still do not see any failure. Can you open a PR adding the test case to the [test file](https://github.com/ember-cli/eslint-plugin-ember/blob/master/tests/lib/rules/no-actions-hash.js) for this rule so we can see if it fails the tests there?

**Comment by bmish** [comment]
@carakessler good news, I found the issue you were referring to, I had to use something like `Route` instead of `Service` to get it to reproduce, opened fix.

**Comment by carakessler** [comment]
Amazing, thank you so much for your due diligence here, it is much appreciated :)
