### ISSUE TITLE
New Rule: Lint against firstObject/lastObject

### ISSUE THREAD

**Issue by mehulkar** [ember-cli/eslint-plugin-ember#922]
it would be good to have a lint rule against usage of firstObject/lastObject so we can start moving to normal JS arrays.

**Comment by bmish** [comment]
Yeah, I'd be in favor of two new rules:
* `no-ember-arrays`
* `no-ember-objects`

**Comment by smilland** [comment]
This can be part of https://github.com/ember-cli/eslint-plugin-ember/issues/1075
