### ISSUE TITLE
ember/no-side-effects doesn't work with plain getters

### ISSUE THREAD

**Issue by lhz516** [ember-cli/eslint-plugin-ember#958]
In Glimmer component, we no longer need `@computed` decorator on a getter.

After removing `@computed`, the rule `no-side-effects` stopped working.

Are there any plans to support this rule without `@computed`?

**Comment by bmish** [comment]
Good idea. I opened #961 to fix this.

**Comment by lhz516** [comment]
Thanks for the quick response! I left a comment in the PR.
