### ISSUE TITLE
Improvement: Support for native ES6 Classes

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/eslint-plugin-ember#96]
Currently `eslint-plugin-ember` only lints standard EmberObject model classes, i.e. `Controller.extend({ ... })`. But native ES6 classes [are on the horizon](https://github.com/rwjblue/ember-decorators#application-usage) and may already be used with [some](https://github.com/rwjblue/ember-decorators/issues/123) [caveats](https://github.com/emberjs/ember.js/blob/7819409b7b6559e9fc0300a29e66a16356fb67a7/packages/ember-runtime/tests/system/object/es-compatibility-test.js).

This code runs without any problems, with the necessary [Babel configuration](https://github.com/rwjblue/ember-decorators#babel-6x):

```js
// Please excuse the German names here. I just copied this from our production app.
import Controller from '@ember/controller';
import { computed } from 'ember-decorators/object';
import { reads } from 'ember-decorators/object/computed';

export default class extends Controller {
  queryParams = {
    posteingangTab: {
      scope: 'controller'
    }
  };

  @reads('model') posteingang;

  @computed('posteingang')
  rezeptkopfdatenIds(posteingang) {
    return posteingang.hasMany('rezeptkopfdaten').ids();
  }
}
```

It would be awesome if this plugin could support both the old and new syntax.

<sub>Also a new rule proposal: `use-es6-classes` :blush: </sub>

**Comment by buschtoens** [comment]
By the way: things you would have passed to `reopenClass({ ... })` can now just use the `static` keyword:

```js
import Component from '@ember/component';

export default class extends Component {
  static positionalParams = ['fooParam', 'barParam'];

  fooParam;
  barParam;
}
```

**Comment by michalsnik** [comment]
Hey, I was thinking about this already @buschtoens , but I'm not sure we want to support it at this moment. We should probably wait until things settle down a bit. But I'm open for a discussion here, maybe we can come up with something good. When I think about this case however I see a tons of work to be done in order to support it without introducing any breaking changes.

**Comment by bmish** [comment]
This has mostly been fixed at this point. Related: #560
