### ISSUE TITLE
Disallow using invalid CSS selectors in test helpers

### ISSUE THREAD

**Issue by jsturgis** [ember-cli/eslint-plugin-ember#979]
Tests which use test-helpers that rely on querySelector or querySelectorAll to lookup an element in the dom are able to use invalid attribute selectors which do not have a closing bracket. This happens to work today due to a quirk in the CSS selector spec and is marked as [WontFix by Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=460399#c6). We should be preventing invalid selectors from being used in test-helpers as they are likely to stop working at some point and are not valid selector syntax.

**Comment by rwjblue** [comment]
This seems good to add, thanks for working on it! I think we should do as much validation as we can of that "selector" argument (which IMHO means doing even more validation than the unclosed attribute checks).

**Comment by jsturgis** [comment]
yeah good idea, quick question do you think we should try to catch selectors that will actually fail tests or only invalid selectors that won't fail tests?

I think if we want to catch any invalid selector which will also fail a test it might be a pretty large set of permutations.

**Comment by rwjblue** [comment]
I think its pretty hard for us to reason about which ones will fail tests vs which won't. We should probably try to find a "selector validation library" that we can use off the shelf and if the first argument to `assert.dom` / `this.element.querySelector` / `this.element.querySelectorAll` is a static string, we validate it.

Is that what you were thinking?

**Comment by jsturgis** [comment]
Ok that's what I was thinking, I've updated the PR so it will validate all selectors using sizzle let me know what you think, thanks!
