### ISSUE TITLE
'ember/no-get-with-default' rule not working in any cases?

### ISSUE THREAD

**Issue by BlueRaja** [ember-cli/eslint-plugin-ember#999]
With `'ember/no-get-with-default'` set to `'error'`, we are not seeing any errors for any of the usages of `getWithDefault`.  

## Repro steps
app/pods/application/route.js
```
import { getWithDefault } from '@ember/object';
import Route from '@ember/routing/route';

export default Route.extend({
  someFunction() {
    const a = {};
    const b = getWithDefault(a, 'test', '');
  },
});
```

Then run `eslint app tests --fix --quiet`

## Expected results
Get an error for `getWithDefault`, or linter fixes it automatically.  
(And get an error for unused `b`)

## Actual results
Only an error for unused `b`

### Versions
```
    "@babel/eslint-parser": "^7.12.1",
    "eslint": "^7.12.1",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-plugin-ember": "^9.5.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-restricted-globals": "~0.2.0",
```

**Comment by bmish** [comment]
@BlueRaja this behavior is because the rule currently only catches usages with `this` and not other Ember objects. But I just opened up #1000 to add options to catch non-`this` usages.
